default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: studio
  password: 123456

development:
  <<: *default
  database: liburanku_development

test:
  <<: *default
  database: liburanku_test

production:
  <<: *default
  database: liburanku_production
  username: liburanku
  password: <%= ENV['LIBURANKU_DATABASE_PASSWORD'] %>
